uint8_t BaseAddress=0x10;
uint8_t CurrentSAMState=0;
uint8_t ClockCount=0;
int CurrentStateSync=0;
int CurrentStateCLK=0;
uint8_t NewSAMState=0;
uint8_t FireOffSAMs=0;
uint8_t FireOnSAMs=0;
//uint8_t BitChangedFiring=0;
int i=0;
uint8_t mask=0;
uint8_t temp=0;
int SAMsFiring=0;
int SAMsNeedFiring=0;
uint8_t MessageCount=0;
const uint8_t SAMorLED=0x00; //0 in the bit means that it needs to be treated as a SAM (momentary)
const uint8_t SAMFireTime=0x03; //in message count
const uint8_t BaseAddressMask=0xF8;
#define bitset(var,bitno) ((var) |= 1UL <<(bitno))
#define bitclr(var,bitno) ((var) &= ~(1UL<<(bitno)))